# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroupDocsAssemblyCloud' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GroupDocsAssemblyCloud
    pod 'Alamofire', '~> 4.7'
end

target 'GroupDocsAssemblyCloudTests' do
  use_frameworks!
  inherit! :search_paths
  # Pods for testing
end
